[devshell]
startup.main.text = "cd nix"

# Here you can specify all Android SDK settings.
# For available options, please see https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/mobile/androidenv/compose-android-packages.nix
[android]
platformToolsVersion = "31.0.3"
buildToolsVersions = [ "30.0.2", "31.0.0" ]
platformVersions = [ "29" ]
abiVersions = [ "armeabi-v7a", "arm64-v8a" ]
ndkVersions = [ "20.0.5594570" ]
cmakeVersions = [ "3.6.4111459" ]
emulatorVersion = "30.8.4"
includeNDK = false
includeEmulator = false
includeSources = false
includeSystemImages = false
useGoogleAPIs = false
useGoogleTVAddOns = false